@echo off
echo Building project...
call bun run build
echo Cleaning old assets...
if exist android\app\src\main\assets\public rmdir /s /q android\app\src\main\assets\public
mkdir android\app\src\main\assets\public
echo Copying new assets...
xcopy /e /y dist\client\* android\app\src\main\assets\public\
echo Syncing Capacitor...
call npx cap sync android
echo Done! Please run the app from Android Studio.
